import { Bot, InlineKeyboard } from "grammy";
import { assessCombinedRisk } from "./core/combined-risk.js";
import { assessRisk } from "./core/risk.js";
import { inspectToken } from "./core/onchain-safety.js";
import { getRiskProfileConfig, parseRiskProfile, type RiskProfile } from "./core/risk-profile.js";
import { isAuthorized, parseAllowedUserIds } from "./security/telegram-auth.js";
import { RateLimiter } from "./security/rate-limit.js";

type Pair = { chainId?: string; url?: string; baseToken?: { symbol?: string; name?: string; address?: string }; priceChange?: { h24?: number }; volume?: { h24?: number }; liquidity?: { usd?: number }; fdv?: number; pairCreatedAt?: number; txns?: { h24?: { buys?: number; sells?: number } } };
const token = process.env.TELEGRAM_BOT_TOKEN;
const allowedChatId = process.env.TELEGRAM_CHAT_ID;
const allowedUserIds = parseAllowedUserIds(process.env.TELEGRAM_ALLOWED_USER_IDS);
const solanaRpcUrl = process.env.SOLANA_RPC_URL;
if (!token) throw new Error("Missing TELEGRAM_BOT_TOKEN");
if (allowedUserIds.size === 0) throw new Error("Missing TELEGRAM_ALLOWED_USER_IDS");
if (!solanaRpcUrl) throw new Error("Missing SOLANA_RPC_URL");
const bot = new Bot(token);
const limiter = new RateLimiter(10_000, 5);
const profiles = new Map<number, RiskProfile>();
const scannedPairs = new Map<string, Pair>();
const MAX_SCANNED_PAIRS = 50;
const profileFor = (id?: number): RiskProfile => profiles.get(id ?? 0) ?? "balanced";
function guard(ctx: { chat?: { id: number }; from?: { id: number } }) { if (!isAuthorized({ chatId: ctx.chat?.id, userId: ctx.from?.id }, allowedUserIds, allowedChatId)) return false; return !limiter.isLimited(`${ctx.from?.id}:${ctx.chat?.id ?? "private"}`); }
function rememberPair(pair: Pair) { const address=pair.baseToken?.address; if(!address)return; scannedPairs.delete(address); scannedPairs.set(address,pair); while(scannedPairs.size>MAX_SCANNED_PAIRS){const oldest=scannedPairs.keys().next().value;if(oldest)scannedPairs.delete(oldest);else break;} }
const money=(n?:number)=>!Number.isFinite(n)?"—":n!>=1e6?`$${(n!/1e6).toFixed(1)}M`:n!>=1e3?`$${(n!/1e3).toFixed(1)}K`:`$${n!.toFixed(0)}`;
const age=(ts?:number)=>{if(!ts)return"unknown";const h=Math.max(0,(Date.now()-ts)/3_600_000);return h<24?`${h.toFixed(0)}h`:`${(h/24).toFixed(1)}d`;};
const score=(p:Pair)=>{const liq=p.liquidity?.usd??0,vol=p.volume?.h24??0,buys=p.txns?.h24?.buys??0,sells=p.txns?.h24?.sells??0,change=p.priceChange?.h24??0;let s=0;if(liq>=100000)s+=30;else if(liq>=25000)s+=22;else if(liq>=10000)s+=12;if(vol>=500000)s+=25;else if(vol>=100000)s+=18;else if(vol>=25000)s+=10;if(buys+sells>0&&buys>sells)s+=Math.min(20,Math.round(buys/(buys+sells)*20));if(change>0&&change<100)s+=10;else if(change>=100)s+=4;if(liq>0&&(p.fdv??0)/liq<100)s+=10;const hours=p.pairCreatedAt?(Date.now()-p.pairCreatedAt)/3_600_000:Infinity;if(hours<2)s-=15;return Math.max(0,Math.min(100,s));};
const menu=()=>new InlineKeyboard().text("🔎 Scan","scan").row().text("💼 Portfolio","portfolio").text("⚙️ Settings","settings").row().text("ℹ️ Help","help");
const settingsMenu=(profile:RiskProfile)=>new InlineKeyboard().text(profile==="conservative"?"✓ 🟢 Conservative":"🟢 Conservative","risk:conservative").row().text(profile==="balanced"?"✓ 🟡 Balanced":"🟡 Balanced","risk:balanced").row().text(profile==="aggressive"?"✓ 🔴 Aggressive":"🔴 Aggressive","risk:aggressive").row().text("← Back","home");
async function scan(profile:RiskProfile){const c=getRiskProfileConfig(profile),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const r=await fetch("https://api.dexscreener.com/latest/dex/search?q=SOL",{signal:controller.signal});if(!r.ok)throw new Error("Market data unavailable");const d=await r.json() as {pairs?:Pair[]};if(!Array.isArray(d.pairs))return[];return d.pairs.filter(p=>p.chainId==="solana"&&(p.liquidity?.usd??0)>=c.minLiquidityUsd&&(p.volume?.h24??0)>=c.minVolume24hUsd&&(c.allowVeryNew||((Date.now()-(p.pairCreatedAt??0))/3_600_000)>=c.minAgeHours)).sort((a,b)=>score(b)-score(a)).slice(0,5);}finally{clearTimeout(timeout);}}
async function sendScan(ctx:any){const profile=profileFor(ctx.from?.id);await ctx.reply(`🔎 Scanning with ${profile} risk settings...`);try{const pairs=await scan(profile);if(!pairs.length){await ctx.reply("No candidates passed the current filters.",{reply_markup:menu()});return;}for(const[pidx,p]of pairs.entries()){rememberPair(p);const buys=p.txns?.h24?.buys??0,sells=p.txns?.h24?.sells??0,address=p.baseToken?.address;const text=[`${pidx+1}. ${p.baseToken?.symbol??"Unknown"} — ${score(p)}/100`,`Liquidity: ${money(p.liquidity?.usd)}   Volume: ${money(p.volume?.h24)}`,`24h: ${p.priceChange?.h24?.toFixed(1)??"—"}%   Buys/Sells: ${buys}/${sells}`,`Age: ${age(p.pairCreatedAt)}   FDV: ${money(p.fdv)}`,p.url?`Market: ${p.url}`:"","⚠️ Research score only — not a buy signal."].filter(Boolean).join("\n");await ctx.reply(text,{reply_markup:address?new InlineKeyboard().text("Analyze",`analyze:${address}`):menu()});}await ctx.reply("Use Analyze for the full risk breakdown. Trading is disabled.",{reply_markup:menu()});}catch{console.error("market scan failed");await ctx.reply("Couldn't fetch market data right now. Try again later.",{reply_markup:menu()});}}
async function showSettings(ctx:any){const p=profileFor(ctx.from?.id);await ctx.reply(`⚙️ Settings\n\nRisk level controls how strict the scanner filters are.\n\nCurrent: ${p}\n\nAggressive never disables risk warnings.`,{reply_markup:settingsMenu(p)});}
bot.command("start",async ctx=>{if(!guard(ctx))return;await ctx.reply("Solana Meme Agent\n\nSimple by design. I scan first; you stay in control.\n\nTrading is disabled for now.",{reply_markup:menu()});});
bot.command("scan",async ctx=>{if(guard(ctx))await sendScan(ctx);});
bot.command("portfolio",async ctx=>{if(guard(ctx))await ctx.reply("💼 No wallet is connected yet. Trading is disabled.",{reply_markup:menu()});});
bot.command("settings",async ctx=>{if(guard(ctx))await showSettings(ctx);});
bot.command("help",async ctx=>{if(guard(ctx))await ctx.reply("Use the buttons or /scan.\n\nThe bot never asks for a seed phrase or private key.\n\nWhen trading is enabled, use a separate trading wallet in Phantom or another mainstream Solana wallet. Do not connect your main wallet.",{reply_markup:menu()});});
bot.callbackQuery("scan",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await sendScan(ctx);});
bot.callbackQuery("portfolio",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("💼 No wallet is connected yet. Trading is disabled.",{reply_markup:menu()});});
bot.callbackQuery("settings",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await showSettings(ctx);});
bot.callbackQuery(/^risk:(conservative|balanced|aggressive)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}const p=ctx.match[1] as RiskProfile;profiles.set(ctx.from.id,p);await ctx.answerCallbackQuery({text:`Risk set to ${p}.`});await showSettings(ctx);});
bot.callbackQuery("home",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("Solana Meme Agent\n\nTrading is disabled for now.",{reply_markup:menu()});});
bot.callbackQuery("help",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("I scan public Solana market data and rank candidates using simple checks. Nothing is bought automatically.\n\nFor future trading: create a separate trading wallet in Phantom (or another mainstream Solana wallet). Do not connect your main wallet. Never share a seed phrase or private key.",{reply_markup:menu()});});
bot.callbackQuery(/^analyze:(.+)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();const address=ctx.match[1],pair=scannedPairs.get(address);if(!pair){await ctx.reply("That scan result has expired. Run /scan again.",{reply_markup:menu()});return;}const market=assessRisk({liquidityUsd:pair.liquidity?.usd??0,volume24hUsd:pair.volume?.h24??0,buys24h:pair.txns?.h24?.buys??0,sells24h:pair.txns?.h24?.sells??0,priceChange24h:pair.priceChange?.h24??0,fdvUsd:pair.fdv??0,ageHours:pair.pairCreatedAt?Math.max(0,(Date.now()-pair.pairCreatedAt)/3_600_000):999999});try{const onchain=await inspectToken(solanaRpcUrl,address);const risk=assessCombinedRisk({liquidityUsd:pair.liquidity?.usd??0,volume24hUsd:pair.volume?.h24??0,buys24h:pair.txns?.h24?.buys??0,sells24h:pair.txns?.h24?.sells??0,priceChange24h:pair.priceChange?.h24??0,fdvUsd:pair.fdv??0,ageHours:pair.pairCreatedAt?Math.max(0,(Date.now()-pair.pairCreatedAt)/3_600_000):999999},onchain);const flags=risk.flags.length?risk.flags.map(f=>`• ${f}`).join("\n"):"• No risk flags triggered";const hard=risk.hardWarnings.length?`\n🚨 Hard warnings:\n${risk.hardWarnings.map(f=>`• ${f}`).join("\n")}`:"";await ctx.reply([`🔎 ${pair.baseToken?.symbol??"Unknown"} analysis`,`Risk: ${risk.label} (${risk.score}/100)`,`Market score: ${risk.market.score}/100`,`On-chain score: ${100-(risk.market.score-risk.score)}/100`,`Liquidity: ${money(pair.liquidity?.usd)}`,`24h volume: ${money(pair.volume?.h24)}`,`24h change: ${pair.priceChange?.h24?.toFixed(1)??"—"}%`,`Pair age: ${age(pair.pairCreatedAt)}`,`Token program: ${onchain.tokenProgram}`,"","Risk flags:",flags,hard,"","⚠️ Screening only — not financial advice or a buy signal."].join("\n"),{reply_markup:menu()});}catch{await ctx.reply("Couldn't verify this token on-chain right now. No safety conclusion is made when verification fails.",{reply_markup:menu()});}});
bot.catch(e=>console.error("Telegram bot error",e));
await bot.api.setMyCommands([{command:"start",description:"Open the main menu"},{command:"scan",description:"Find Solana candidates"},{command:"portfolio",description:"View portfolio"},{command:"settings",description:"Scanner settings"},{command:"help",description:"Show help"}]);
console.log("Solana Telegram Agent running");
await bot.start();
