import { Bot, InlineKeyboard } from "grammy";
import { scanSources, type PipelineResult } from "./core/scanner-pipeline.js";
import { assessCombinedRisk } from "./core/combined-risk.js";
import { inspectToken } from "./core/onchain-safety.js";
import { classifyCandidate } from "./core/candidate.js";
import { assessIntelligence } from "./core/intelligence.js";
import { searchX, type XPost } from "./core/x-signals.js";
import { type RiskProfile } from "./core/risk-profile.js";
import { RiskProfileStore } from "./core/risk-profile-store.js";
import { WatchlistStore } from "./core/watchlist-store.js";
import { detectAlert, snapshotFromPair, type AlertSnapshot } from "./core/alert-rules.js";
import { applySafetyGate } from "./core/safety-gate.js";
import { isAuthorized, parseAllowedUserIds } from "./security/telegram-auth.js";
import { RateLimiter } from "./security/rate-limit.js";

const token = process.env.TELEGRAM_BOT_TOKEN;
const allowedChatId = process.env.TELEGRAM_CHAT_ID;
const allowedUserIds = parseAllowedUserIds(process.env.TELEGRAM_ALLOWED_USER_IDS);
const solanaRpcUrl = process.env.SOLANA_RPC_URL;
const xBearerToken = process.env.X_BEARER_TOKEN;
if (!token) throw new Error("Missing TELEGRAM_BOT_TOKEN");
if (allowedUserIds.size === 0) throw new Error("Missing TELEGRAM_ALLOWED_USER_IDS");
if (!solanaRpcUrl) throw new Error("Missing SOLANA_RPC_URL");
const bot = new Bot(token);
const limiter = new RateLimiter(10_000, 5);
const riskProfiles = new RiskProfileStore(process.env.RISK_PROFILE_FILE ?? "data/risk-profiles.json");
const watchlists = new WatchlistStore(process.env.WATCHLIST_FILE ?? "data/watchlists.json");
const scannedPairs = new Map<string, PipelineResult & { xPosts?: XPost[] }>();
const snapshots = new Map<string, AlertSnapshot>();
const MAX_SCANNED_PAIRS = 50;
const profileFor = async (id?: number): Promise<RiskProfile> => id ? riskProfiles.get(id) : "balanced";
function guard(ctx: { chat?: { id: number }; from?: { id: number } }) { if (!isAuthorized({ chatId: ctx.chat?.id, userId: ctx.from?.id }, allowedUserIds, allowedChatId)) return false; return !limiter.isLimited(`${ctx.from?.id}:${ctx.chat?.id ?? "private"}`); }
function rememberPair(pair: PipelineResult & { xPosts?: XPost[] }) { const address=pair.baseToken?.address; if(!address)return; scannedPairs.delete(address); scannedPairs.set(address,pair); while(scannedPairs.size>MAX_SCANNED_PAIRS){const oldest=scannedPairs.keys().next().value;if(oldest)scannedPairs.delete(oldest);else break;} }
const money=(n?:number)=>!Number.isFinite(n)?"—":n!>=1e6?`$${(n!/1e6).toFixed(1)}M`:n!>=1e3?`$${(n!/1e3).toFixed(1)}K`:`$${n!.toFixed(0)}`;
const age=(ts?:number)=>{if(!ts)return"unknown";const h=Math.max(0,(Date.now()-ts)/3_600_000);return h<24?`${h.toFixed(0)}h`:`${(h/24).toFixed(1)}d`;};
const menu=()=>new InlineKeyboard().text("🔎 Scan","scan").row().text("👁 Watchlist","watchlist").text("💼 Portfolio","portfolio").row().text("⚙️ Settings","settings").text("ℹ️ Help","help");
const settingsMenu=(profile:RiskProfile)=>new InlineKeyboard().text(profile==="conservative"?"✓ 🟢 Conservative":"🟢 Conservative","risk:conservative").row().text(profile==="balanced"?"✓ 🟡 Balanced":"🟡 Balanced","risk:balanced").row().text(profile==="aggressive"?"✓ 🔴 Aggressive":"🔴 Aggressive","risk:aggressive").row().text("← Back","home");
async function socialFor(pair: PipelineResult): Promise<XPost[]> { if (!xBearerToken || !pair.baseToken?.symbol) return []; try { return await searchX(`$${pair.baseToken.symbol} OR ${pair.baseToken.symbol} Solana`, xBearerToken); } catch { return []; } }
function candidateLabel(c:string){return c==="interesting"?"INTERESTING":c==="momentum"?"MOMENTUM":c==="caution"?"CAUTION":"WEAK";}
function alertText(events: string[]) { return events.map(e=>e==="momentum_jump"?"Momentum jumped":e==="opportunity_jump"?"Opportunity score jumped":e==="price_move"?"Large price move detected":"Risk deteriorated").join(" · "); }
async function sendScan(ctx:any){const profile=await profileFor(ctx.from?.id);await ctx.reply(`🔎 Scanning with ${profile} risk settings...`);try{const pairs=await scanSources(profile);if(!pairs.length){await ctx.reply("No candidates passed the current filters.",{reply_markup:menu()});return;}for(const[pidx,p]of pairs.entries()){const candidate=classifyCandidate(p),xPosts=await socialFor(p),intelligence=assessIntelligence(candidate,xPosts);const enriched={...p,xPosts};rememberPair(enriched);const address=p.baseToken?.address;if(address){const previous=snapshots.get(address),current=snapshotFromPair(p);const events=detectAlert(previous,current);snapshots.set(address,current);if(events.length) await ctx.reply(`🔔 ${p.baseToken?.symbol??"Token"}: ${alertText(events)}`);}
const source=p.source==="pumpfun"?`Pump.fun · ${p.pumpfunStage??"unknown"}${p.pumpfunMayhemMode?" · Mayhem Mode":""}`:"DexScreener";const socialText=xBearerToken?`X signal: ${intelligence.x.score}/100 (${intelligence.x.confidence})`:`X signal: unavailable`;const text=[`${pidx+1}. ${p.baseToken?.symbol??"Unknown"} — ${candidateLabel(candidate.classification)}`,`Source: ${source}`,`Intelligence ${intelligence.score}/100 · Opportunity ${p.opportunityScore}/100`,`Momentum ${p.momentum.score}/100 · ${socialText}`,`Liquidity: ${money(p.liquidity?.usd)}   Volume: ${money(p.volume?.h24)}`,`24h: ${p.priceChange?.h24?.toFixed(1)??"—"}%   Age: ${age(p.pairCreatedAt)}`,`Why: ${intelligence.reasons.slice(0,2).join(" · ")}`,p.source==="pumpfun"&&p.pumpfunMayhemMode?"⚠️ Mayhem Mode can distort early price action.":"","⚠️ Intelligence is not safety and is not a buy signal."].filter(Boolean).join("\n");await ctx.reply(text,{reply_markup:address?new InlineKeyboard().text("Analyze safety",`analyze:${address}`).text("＋ Watch",`watch:${address}`):menu()});}await ctx.reply("Analyze safety before considering any candidate. Trading is disabled.",{reply_markup:menu()});}catch(error){console.error("market scan failed",error);await ctx.reply("Couldn't fetch market data right now. Try again later.",{reply_markup:menu()});}}
async function showWatchlist(ctx:any){const items=await watchlists.list(ctx.from.id);if(!items.length){await ctx.reply("👁 Watchlist is empty. Use ＋ Watch on a scan result.",{reply_markup:menu()});return;}const keyboard=new InlineKeyboard();items.forEach((x,i)=>{keyboard.text(`${i+1}. ${x.label??x.address.slice(0,8)}…`,`watchinfo:${x.address}`).text("×",`unwatch:${x.address}`).row();});keyboard.text("← Back","home");await ctx.reply("👁 Watchlist\n\nSelect a token to inspect or × to remove it.",{reply_markup:keyboard});}
async function showSettings(ctx:any){const p=await profileFor(ctx.from?.id);await ctx.reply(`⚙️ Settings\n\nRisk level controls how strict the scanner filters are.\n\nCurrent: ${p}\n\nAggressive never disables risk warnings. Your setting is saved across restarts.`,{reply_markup:settingsMenu(p)});}
bot.command("start",async ctx=>{if(!guard(ctx))return;await ctx.reply("Solana Meme Agent\n\nSimple by design. I scan first; you stay in control.\n\nTrading is disabled for now.",{reply_markup:menu()});});
bot.command("scan",async ctx=>{if(guard(ctx))await sendScan(ctx);});
bot.command("watchlist",async ctx=>{if(guard(ctx))await showWatchlist(ctx);});
bot.command("portfolio",async ctx=>{if(guard(ctx))await ctx.reply("💼 No wallet is connected yet. Trading is disabled.",{reply_markup:menu()});});
bot.command("settings",async ctx=>{if(guard(ctx))await showSettings(ctx);});
bot.command("help",async ctx=>{if(guard(ctx))await ctx.reply("Use the buttons or /scan.\n\nWatchlist saves token addresses for later review. Alerts are informational and only trigger on meaningful signal changes.\n\nThe bot never asks for a seed phrase or private key.\n\nTrading is disabled in this version.",{reply_markup:menu()});});
bot.callbackQuery("scan",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await sendScan(ctx);});
bot.callbackQuery("watchlist",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await showWatchlist(ctx);});
bot.callbackQuery(/^watch:(.+)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}const address=ctx.match[1];const pair=scannedPairs.get(address);const added=await watchlists.add(ctx.from.id,address,pair?.baseToken?.symbol);await ctx.answerCallbackQuery({text:added?"Added to watchlist.":"Already on watchlist."});await showWatchlist(ctx);});
bot.callbackQuery(/^unwatch:(.+)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await watchlists.remove(ctx.from.id,ctx.match[1]);await ctx.answerCallbackQuery({text:"Removed."});await showWatchlist(ctx);});
bot.callbackQuery(/^watchinfo:(.+)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}const pair=scannedPairs.get(ctx.match[1]);await ctx.answerCallbackQuery();if(!pair){await ctx.reply("This token is not in the current scan cache. Run /scan to refresh it.",{reply_markup:menu()});return;}await ctx.reply(`${pair.baseToken?.symbol??"Token"}\nSource: ${pair.source}\nOpportunity ${pair.opportunityScore}/100\nMomentum ${pair.momentum.score}/100\nLiquidity ${money(pair.liquidity?.usd)}\n\nRun Analyze safety from a fresh scan before considering any action.`,{reply_markup:menu()});});
bot.callbackQuery("portfolio",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("💼 No wallet is connected yet. Trading is disabled.",{reply_markup:menu()});});
bot.callbackQuery("settings",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await showSettings(ctx);});
bot.callbackQuery(/^risk:(conservative|balanced|aggressive)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}const p=ctx.match[1] as RiskProfile;await riskProfiles.set(ctx.from.id,p);await ctx.answerCallbackQuery({text:`Risk set to ${p}.`});await showSettings(ctx);});
bot.callbackQuery("home",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("Solana Telegram Agent\n\nTrading is disabled for now.",{reply_markup:menu()});});
bot.callbackQuery("help",async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();await ctx.reply("I scan public Solana market data and rank candidates using market, momentum and optional X signals. Nothing is bought automatically.",{reply_markup:menu()});});
bot.callbackQuery(/^analyze:(.+)$/,async ctx=>{if(!guard(ctx)){await ctx.answerCallbackQuery({text:"Not authorized or rate limited."});return;}await ctx.answerCallbackQuery();const address=ctx.match[1],pair=scannedPairs.get(address);if(!pair){await ctx.reply("That scan result has expired. Run /scan again.",{reply_markup:menu()});return;}try{const onchain=await inspectToken(solanaRpcUrl,address);const market={liquidityUsd:pair.liquidity?.usd??0,volume24hUsd:pair.volume?.h24??0,buys24h:pair.txns?.h24?.buys??0,sells24h:pair.txns?.h24?.sells??0,priceChange24h:pair.priceChange?.h24??0,fdvUsd:pair.fdv??0,ageHours:pair.pairCreatedAt?Math.max(0,(Date.now()-pair.pairCreatedAt)/3_600_000):999999};const risk=assessCombinedRisk(market,onchain);const gate=applySafetyGate(classifyCandidate(pair),risk.score,risk.hardWarnings);const intelligence=assessIntelligence(classifyCandidate(pair),pair.xPosts??[]);const previous=snapshots.get(address);snapshots.set(address,snapshotFromPair(pair,risk.score));const flags=risk.flags.length?risk.flags.map(f=>`• ${f}`).join("\n"):"• No risk flags triggered";const hard=risk.hardWarnings.length?`\n🚨 Hard warnings:\n${risk.hardWarnings.map(f=>`• ${f}`).join("\n")}`:"";await ctx.reply([`🔎 ${pair.baseToken?.symbol??"Unknown"} analysis`,`Source: ${pair.source}${pair.pumpfunStage?` · ${pair.pumpfunStage}`:""}`,`Decision: ${gate.decision.toUpperCase()}`,`Risk: ${risk.label} (${risk.score}/100)`,`Intelligence: ${intelligence.score}/100`,`Market: ${risk.market.score}/100 · On-chain: ${risk.onchainScore}/100`,`Opportunity: ${pair.opportunityScore}/100 · Momentum: ${pair.momentum.score}/100`,`X: ${intelligence.x.score}/100 (${intelligence.x.confidence})`,`Liquidity: ${money(pair.liquidity?.usd)}`,`Token program: ${onchain.tokenProgram}`,"","Risk flags:",flags,hard,"",previous?"Signal snapshot updated.":"First safety snapshot recorded.","⚠️ Screening only — not financial advice or a buy signal."].join("\n"),{reply_markup:menu()});}catch{await ctx.reply("Couldn't verify this token on-chain right now. No safety conclusion is made when verification fails.",{reply_markup:menu()});}});
bot.catch(e=>console.error("Telegram bot error",e));
await bot.api.setMyCommands([{command:"start",description:"Open the main menu"},{command:"scan",description:"Find Solana candidates"},{command:"watchlist",description:"View watched tokens"},{command:"portfolio",description:"View portfolio"},{command:"settings",description:"Scanner settings"},{command:"help",description:"Show help"}]);
console.log("Solana Telegram Agent running");
await bot.start();